(setq projectile-globally-ignored-directories '(".idea"
                                                ".ensime_cache"
                                                ".eunit"
                                                ".git"
                                                ".hg"
                                                ".fslckout"
                                                "_FOSSIL_"
                                                ".bzr"
                                                "_darcs"
                                                ".tox"
                                                ".svn"
                                                ".stack-work"
                                                "node_modules"))
